name: 'Install dependencies'

runs:
  using: 'composite'
  steps:

    - name: Install Root repo dependencies
      run: yarn --frozen-lockfile
      shell: bash

  - name: Cache Node.js modules for linting (optional, separate cache)
      uses: actions/cache@v4
      with:
        path: ~/.yarn/cache
        key: ${{ runner.os }}-lint-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-lint-
      shell: bash