name: SonarQube scan

runs:
  using: 'composite'
  steps:
    - name: Extract SonarQube Project Key
      id: extract-key
      run: |
        SONAR_PROJECT_KEY=$(grep '^sonar.projectKey=' sonar-project.properties | cut -d'=' -f2-)
        echo "SONAR_PROJECT_KEY=${SONAR_PROJECT_KEY}" >> $GITHUB_ENV
      shell: bash

    - name: Install SonarQube Scanner
      run: |
        brew install sonar-scanner
      shell: bash

    - name: Perform SonarQube scan
      run: |
        sonar-scanner \
          -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }} \
          -Dsonar.sources=. \
          -Dsonar.host.url=${{ env.SONARQUBE_HOST }} \
          -Dsonar.login=${{ env.SONARQUBE_TOKEN }} \
          -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} \
          -Dsonar.pullrequest.branch=${{ github.head_ref }} \
          -Dsonar.pullrequest.base=${{ github.base_ref }}
      shell: bash

    - name: SonarQube quality gate check
      uses: SonarSource/sonarqube-quality-gate-action@master
      with:
        scanMetadataReportFile: .scannerwork/report-task.txt
      env:
        SONAR_TOKEN: ${{ env.SONARQUBE_TOKEN }}
        SONAR_HOST_URL: ${{ env.SONARQUBE_HOST }}
