Documentation:
  - changed-files:
      - any-glob-to-any-file: '**/*.md'
  color: 'fbca04'  # Yellow

source:
  - all:
      - changed-files:
          - any-glob-to-any-file: 'src/**/*'
          - all-globs-to-all-files: '!src/docs/*'

feature:
  - head-branch: ['^feature', 'feature']
  color: '1d76db'  # Blue

release:
  - base-branch: 'main'
  color: '2cbe4e'  # Green

api:
  - changed-files:
      - any-glob-to-any-file: 'api/*'

bug:
  - head-branch: ['^bugfix/', '^bug/', '^fix/']

config:
  - head-branch: ['^misc/', '^config/', '^others/']

enhancement:
  - head-branch: ['^enhancement/', '^enhance/', '^improvement/', '^improve/']

nfr:
  - changed-files:
      - any-glob-to-any-file: 'nfr/*'

refactor:
  - head-branch: ['^refactor/', '^cleanup/']

ui-component:
  - changed-files:
      - any-glob-to-any-file: 'ui/*'
  color: 'cc6699'  # Pink

ci-cd:
  - changed-files:
      - any-glob-to-any-file: '.github/**/*'
  color: '7057ff'  # Bright purple
