Documentation:
  - changed-files:
      - any-glob-to-any-file: '**/*.md'

source:
  - all:
      - changed-files:
          - any-glob-to-any-file: 'src/**/*'
          - all-globs-to-all-files: '!src/docs/*'

feature:
  - head-branch: ['^feature', 'feature']

release:
  - base-branch: 'main'

api:
  - changed-files:
      - any-glob-to-any-file: 'api/*'

bug:
  - head-branch: ['^bugfix/', '^bug/', '^fix/']

config:
  - head-branch: ['src/^misc/', 'src/^config/']
  - all:
      - changed-files:
          - any-glob-to-any-file: 'configuration/**/*'

enhancement:
  - head-branch: ['^enhancement/', '^enhance/', '^improvement/', '^improve/']

nfr:
  - changed-files:
      - any-glob-to-any-file: 'nfr/*'

refactor:
  - head-branch: ['^refactor/', '^cleanup/']

ui-component:
  - changed-files:
      - any-glob-to-any-file:
          [
            'src/ui/**/*',
            'src/screens/**/*',
            'src/components/**/*',
            'src/themes/**/*'
          ]

utility:
  - changed-files:
      - any-glob-to-any-file: ['src/utils/*']

ci-cd:
  - changed-files:
      - any-glob-to-any-file: ['.github/**/*', 'fastlane/**/*', 'scripts/**/*']

unit-test:
  - changed-files:
      - any-glob-to-any-file: '__tests__/*'
