api: api/*
bug: ['bugfix/*', 'bug/*', 'fix/*']
config: ['misc/*', 'config/*', 'others/*']
enhancement: ['enhancement/*', 'enhance/*', 'improvement/*', 'improve/*']
feature: ['feature/*', 'feat/*']
nfr: nfr/*
refactor: ['refactor/*', 'cleanup/*']
release: release/*
ui-component: ui/*
OCD: feature/OCD/*
