name: 'Common Setup'
description: 'Checkout repository and restore node_modules cache'
runs:
  using: 'composite'
  steps:
    - name: Restore node_modules from cache
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-
