name: 'Build iOS'
description: 'Build iOS app'

runs:
  using: 'composite'
  steps:
    - name: Install CocoaPods dependencies
      run: |
        cd ios
        pod install
      shell: bash

    - name: Install and Build SDK for iOS
      run: |
        yarn react-native bundle --platform ios --dev false --entry-file index.js --bundle-output ios/main.jsbundle --assets-dest ios
      shell: bash

    - name: Set up Xcode
      run: sudo xcode-select --switch /Applications/Xcode_15.3.app # Replace with your Xcode version
      shell: bash

    - name: Build iOS Release
      run: |
        cd ios
        xcodebuild -workspace ${{ env.APP_NAME }}.xcworkspace -scheme ${{ env.APP_NAME }} -sdk iphoneos -configuration Release -archivePath $PWD/build/${{ env.APP_NAME }}.xcarchive archive
      shell: bash

    - name: Export iOS Archive
      run: |
        xcodebuild -exportArchive -archivePath $PWD/build/${{ env.APP_NAME }}.xcarchive -exportOptionsPlist $PWD/ios/exportOptions.plist -exportPath $PWD/build
      shell: bash

    - name: Rename IPA with Repository Name
      run: |
        mv ios/build/*.ipa ios/build/${{ env.APP_NAME }}.ipa
      shell: bash

    - name: Upload iOS Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-release
        path: ios/build/*.ipa
