name: Upload APK version

inputs:
  AUTHORIZATION:
    description: 'Authorization token'
    required: true
  APP_DEV_TOKEN:
    description: 'Application dev token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Debug file existence
      run: |
        echo "Current directory:"
        pwd
        echo "Checking for build outputs:"
        ls -R ${{ env.ANDROID_BUILD_DIR }}
        if [ -f "${{ env.ANDROID_INFO_FILE }}" ]; then
          echo "output-metadata.json exists"
          cat ${{ env.ANDROID_INFO_FILE }}
        else
          echo "output-metadata.json does not exist"
        fi
        if [ -f "${{ env.ANDROID_BUILD_FILE }}" ]; then
          echo "app-release.apk exists"
        else
          echo "app-release.apk does not exist"
        fi
      shell: bash

    - name: Set permissions
      run: |
        if [ -f "${{ env.ANDROID_INFO_FILE }}" ]; then
          chmod 644 ${{ env.ANDROID_INFO_FILE }}
        fi
        if [ -f "${{ env.ANDROID_BUILD_FILE }}" ]; then
          chmod 644 ${{ env.ANDROID_BUILD_FILE }}
        fi
      shell: bash

    - name: Upload the application on Mstore
      env:
        MSTORE_AUTHORIZATION: ${{ inputs.AUTHORIZATION }}
        MSTORE_APP_DEV_TOKEN: ${{ inputs.APP_DEV_TOKEN }}
      run: |
        fastlane upload_to_mstore
      shell: bash
