name: Upload APK Version

runs:
  using: 'composite'
  steps:
    - name: Download Android Artifacts
      uses: actions/download-artifact@v4
      with:
        name: android-release
        path: ${{ env.BUILD_DIR }}

    - name: Debug File Existence
      run: |
        set -e  # Exit immediately if a command exits with a non-zero status.
        echo "Current directory:"
        pwd
        echo "Checking for build outputs:"
        ls -R ${{ env.BUILD_DIR }}
        echo "INFO_FILE: ${{ env.INFO_FILE }}"
        echo "BUILD_FILE: ${{ env.BUILD_FILE }}"
        if [ -f "${{ env.INFO_FILE }}" ]; then
          echo "output-metadata.json exists"
          cat ${{ env.INFO_FILE }}
        else
          echo "output-metadata.json does not exist"
          exit 1
        fi
        if [ -f "${{ env.BUILD_FILE }}" ]; then
          echo "app-release.apk exists"
          ls -l ${{ env.BUILD_FILE }}
        else
          echo "app-release.apk does not exist"
          exit 1
        fi
      shell: bash

    - name: Set Permissions
      run: |
        set -e  # Exit immediately if a command exits with a non-zero status.
        chmod 644 ${{ env.INFO_FILE }} ${{ env.BUILD_FILE }}
        echo "Set permissions for ${{ env.INFO_FILE }} and ${{ env.BUILD_FILE }}"
      shell: bash

    - name: Upload the application on Mstore
      run: |
        bundle execfastlane upload_android_to_mstore
      shell: bash
