name: Upload APK Version

runs:
  using: 'composite'
  steps:
    - name: Download Android Artifacts
      uses: actions/download-artifact@v4
      with:
        name: android-release
        path: ${{ env.ANDROID_BUILD_DIR }}

    - name: Debug File Existence
      run: |
        set -e  # Exit immediately if a command exits with a non-zero status.
        echo "Current directory:"
        pwd
        echo "Checking for build outputs:"
        ls -R ${{ env.ANDROID_BUILD_DIR }}
        echo "ANDROID_INFO_FILE: ${{ env.ANDROID_INFO_FILE }}"
        echo "ANDROID_BUILD_FILE: ${{ env.ANDROID_BUILD_FILE }}"
        if [ -f "${{ env.ANDROID_INFO_FILE }}" ]; then
          echo "output-metadata.json exists"
          cat ${{ env.ANDROID_INFO_FILE }}
        else
          echo "output-metadata.json does not exist"
          exit 1
        fi
        if [ -f "${{ env.ANDROID_BUILD_FILE }}" ]; then
          echo "app-release.apk exists"
          ls -l ${{ env.ANDROID_BUILD_FILE }}
        else
          echo "app-release.apk does not exist"
          exit 1
        fi
      shell: bash

    - name: Set Permissions
      run: |
        set -e  # Exit immediately if a command exits with a non-zero status.
        chmod 644 ${{ env.ANDROID_INFO_FILE }} ${{ env.ANDROID_BUILD_FILE }}
        echo "Set permissions for ${{ env.ANDROID_INFO_FILE }} and ${{ env.ANDROID_BUILD_FILE }}"
      shell: bash

    - name: Upload the application on Mstore
      run: |
        bundle execfastlane upload_android_to_mstore
      shell: bash
