name: 'Build IOS'

runs:
  using: 'composite'
  steps:
    - name: Restore node modules from cache
      uses: ./.github/actions/cache-restore
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6.10'
        bundler-cache: false  # Disable built-in caching
    - name: Build iOS with Fastlane
      run: |
        fastlane ios build
      shell: bash

    - name: Upload iOS Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-release
        path: ${{ env.IOS_BUILD_FILE }}
