name: 'Enhanced Teams Notification'
description: 'Send a beautifully formatted build status notification to Microsoft Teams'

inputs:
  status:
    description: 'Job status'
    required: true
  webhook_url:
    description: 'Microsoft Teams webhook URL'
    required: true
  custom_message:
    description: 'Custom message to include in the notification'
    required: false
    default: ''
  android_version_url:
    description: 'URL for the Android version'
    required: false
  ios_version_url:
    description: 'URL for the iOS version'
    required: false
  commit_sha:
    description: 'SHA of the commit that triggered the workflow'
    required: true
  repo_name:
    description: 'Name of the repository'
    required: true
  branch_name:
    description: 'Name of the branch'
    required: true
  workflow_name:
    description: 'Name of the workflow'
    required: true
  pusher:
    description: 'Name of the pusher'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Send Enhanced Teams Notification
      shell: bash
      env:
        STATUS: ${{ inputs.status }}
        WEBHOOK_URL: ${{ inputs.webhook_url }}
        CUSTOM_MESSAGE: ${{ inputs.custom_message }}
        ANDROID_VERSION_URL: ${{ inputs.android_version_url }}
        IOS_VERSION_URL: ${{ inputs.ios_version_url }}
        COMMIT_SHA: ${{ inputs.commit_sha }}
        REPO_NAME: ${{ inputs.repo_name }}
        BRANCH_NAME: ${{ inputs.branch_name }}
        WORKFLOW_NAME: ${{ inputs.workflow_name }}
        PUSHER: ${{ inputs.pusher }}
      run: |
        if [ "$STATUS" = "success" ]; then
          COLOR="00FF00"
          TITLE="✅ Build Succeeded"
          STATUS_ICON="&#x2705;"
          MESSAGE_TEXT="$CUSTOM_MESSAGE"
        else
          COLOR="FF0000"
          TITLE="❌ Build Failed"
          STATUS_ICON="&#x274C;"
          MESSAGE_TEXT=""
        fi

        # Truncate commit SHA
        SHORT_SHA="${COMMIT_SHA:0:7}"

        # Create version links section
        VERSION_LINKS=""
        if [ -n "$ANDROID_VERSION_URL" ]; then
           VERSION_LINKS="${VERSION_LINKS}\n- **Android Version**: [$ANDROID_VERSION_URL]($ANDROID_VERSION_URL)"
        fi
        if [ -n "$IOS_VERSION_URL" ]; then
          VERSION_LINKS="${VERSION_LINKS}\n- **iOS Version**: [$IOS_VERSION_URL]($IOS_VERSION_URL)"
        fi

        PAYLOAD=$(cat << EOF
        {
          "@type": "MessageCard",
          "@context": "http://schema.org/extensions",
          "themeColor": "$COLOR",
          "summary": "$TITLE",
          "sections": [
            {
              "activityTitle": "$TITLE",
              "activitySubtitle": "GitHub Actions Workflow: $WORKFLOW_NAME",
              "activityImage": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
              "facts": [
                {
                  "name": "Status",
                  "value": "$STATUS_ICON $STATUS"
                },
                {
                  "name": "Repository",
                  "value": "$REPO_NAME"
                },
                {
                  "name": "Branch",
                  "value": "$BRANCH_NAME"
                },
                {
                  "name": "Commit",
                  "value": "(https://github.com/$REPO_NAME/commit/$COMMIT_SHA)"
                },
                 {
                  "name": "Triggered By",
                  "value": "$PUSHER"
                }
              ],
              "text": "$MESSAGE_TEXT$VERSION_LINKS",
              "markdown": true
            }
          ],
          "potentialAction": [
            {
              "@type": "OpenUri",
              "name": "View Workflow",
              "targets": [
                {
                  "os": "default",
                  "uri": "https://github.com/$REPO_NAME/actions/runs/${{ github.run_id }}"
                }
              ]
            }
          ]
        }
        EOF
        )

        curl -H "Content-Type: application/json" -d "$PAYLOAD" "$WEBHOOK_URL"
