name: Upload APK version

runs:
  using: 'composite'
  steps:
    - name: Upload the application on Mstore
      run: |
        curl -X POST https://store.mobelite.fr/console/api_dev.php/api/upload_version \
        -H "Authorization: $AUTHORIZATION" \
        -F "applicationToken=$APP_DEV_TOKEN" \
        -F "fileInfo=@${{ env.info-file }}" \
        -F "file=@${{ env.build-file }}"
      shell: bash
