name: 'Install and Build SDK'
description: 'Runs yarn install for all the packages and sample and fails if yarn lock has a change that is not committed'

runs:
  using: 'composite'
  steps:
    - name: Install Root repo dependencies
      run: yarn --frozen-lockfile
      shell: bash

    - name: Create assets directory for Android
      run: mkdir -p android/app/src/main/assets
      shell: bash

    - name: Build JavaScript bundle for Android
      run: |
        yarn react-native bundle \
          --platform android \
          --dev false \
          --entry-file index.js \
          --bundle-output android/app/src/main/assets/index.android.bundle \
          --assets-dest android/app/src/main/res
      shell: bash

    - name: Install CocoaPods dependencies
      run: |
        cd ios
        pod install
      shell: bash
