name: Install dependencies

runs:
  using: 'composite'
  steps:
    - name: Run tests with coverage
      run: yarn test --coverage
      shell: bash

    - name: Run type check
      run: yarn typecheck
      shell: bash

    - name: Setup environment
      run: |
        chmod +x .github/scripts/load-env-vars.sh
        .github/scripts/load-env-vars.sh
      shell: bash

    - name: Set APP_NAME without username
      run: |
        chmod +x .github/scripts/set_app_name.sh
        .github/scripts/set_app_name.sh
      shell: bash
