name: Install dependencies and setup environment

runs:
  using: 'composite'
  steps:
    - name: Run tests with coverage
      run: yarn test --coverage
      shell: bash

    - name: Run type check
      run: yarn typecheck
      shell: bash

    - name: Set up environment variables from .env file
      id: env
      run: |
        echo "Setting up environment variables..."
        if [ -f .env ]; then
          export $(grep -v '^#' .env | xargs)
          echo "::set-output name=ENV::$ENV"
        else
          echo ".env file not found."
          exit 1
        fi
      shell: bash
