name: 'Install dependencies'

runs:
  using: 'composite'
  steps:
    - name: Run tests with coverage
      run: yarn test --coverage
      shell: bash

    - name: Run type check
      run: yarn typecheck
      shell: bash

    - name: Check Environment Variable
      run: |
        if [[ "${{ env.ENV }}" != "satging" ]]; then
          echo "Environment variable ENV is not set to DEVELOPMENT. Exiting..."
          exit 1
        fi
      shell: bash
