name: 'Install dependencies'

runs:
  using: 'composite'
  steps:
    - name: Restore node_modules from cache
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-

    - name: Run tests with coverage
      run: yarn test --coverage
      shell: bash

    - name: Run type check
      run: yarn typecheck
      shell: bash

    - name: Check Environment Variable
      run: |
        if [[ "${{ env.ENV }}" != "DEVELOPMENT" ]]; then
          echo "Environment variable ENV is not set to DEVELOPMENT. Exiting..."
          exit 1
        fi
      shell: bash
