name: 'Set up deploy environment'
description: 'Determine deploy env build and info based on platform'

runs:
  using: composite
  steps:
    - name: Set up deploy environment
      id: setup_deploy_env
      run: |

        # Extract the app name from the package.json file
        APP_NAME=$(jq -r '.name' ${{ github.workspace }}/package.json)

        if [ "${{ matrix.platform }}" == "android" ]; then
          echo "APP_DEV_TOKEN=${{ secrets.APP_DEV_TOKEN }}" >> $GITHUB_ENV
          # Set up the file paths for Android
          INFO_FILE="${{ github.workspace }}/output-metadata.json"
          BUILD_FILE="${{ github.workspace }}/${APP_NAME}-${{ env.ENVIRONMENT }}.apk"
        elif [ "${{ matrix.platform }}" == "ios" ]; then
          echo "APP_DEV_TOKEN=${{ secrets.IOS_APP_DEV_TOKEN }}" >> $GITHUB_ENV
          # Set up the file paths for iOS
          INFO_FILE="${{ github.workspace }}/ios/${APP_NAME}/info.plist"
          BUILD_FILE="${{ github.workspace }}/${APP_NAME}.ipa"
        fi

        # Ensure the files are found
        if [ ! -f "$INFO_FILE" ] || [ ! -f "$BUILD_FILE" ]; then
          echo "Error: Required files not found!"
          exit 1
        fi

        echo "INFO_FILE=$INFO_FILE" >> $GITHUB_ENV
        echo "BUILD_FILE=$BUILD_FILE" >> $GITHUB_ENV
      shell: bash
