name: 'Set up deploy environment'
description: 'Determine deploy env build and info based on platform'
inputs:
  build_dir:
    description: 'Directory where the build artifacts are stored'
    required: true

runs:
  using: composite
  steps:
    - name: Print build_dir
      run: |
        echo "Build directory: ${{ inputs.build_dir }}"
      shell: bash

    - name: Setup deploy environment for Android
      if: ${{ env.PLATFORM == 'android' }}
      run: |
        BUILD_FILE=$(find "${{ inputs.build_dir }}" -name "*.apk" | head -n 1)
        INFO_FILE=$(find "${{ inputs.build_dir }}" -name "*.json" | head -n 1)

        if [[ -f "$BUILD_FILE" && -f "$INFO_FILE" ]]; then
          echo "BUILD_FILE=$BUILD_FILE" >> $GITHUB_OUTPUT
          echo "INFO_FILE=$INFO_FILE" >>  $GITHUB_OUTPUT
        else
          echo "Required files not found!" >&2
          exit 1
        fi
      shell: bash


    - name: Setup deploy environment for iOS
      if: ${{ env.PLATFORM == 'ios' }}
      run: |
        BUILD_FILE=$(find "${{ inputs.build_dir }}" -name "*.ipa" | head -n 1)
        INFO_FILE=$(find "${{ inputs.build_dir }}" -name "*.plist" | head -n 1)

        if [[ -f "$BUILD_FILE" && -f "$INFO_FILE" ]]; then
          echo "BUILD_FILE=$BUILD_FILE" >> $GITHUB_OUTPUT
          echo "INFO_FILE=$INFO_FILE" >> $GITHUB_OUTPUT
        else
          echo "Required files not found!" >&2
          exit 1
        fi
      shell: bash
