name: 'Set up deploy environment'
description: 'Determine deploy env build and info based on platform'

outputs:
  BUILD_DIR:
    description: 'Directory where the build artifacts are located'
    value: ${{ steps.set-build-dir.outputs.BUILD_DIR }}
  ARTIFACT_NAME:
    description: 'Name of the artifact to be uploaded'
    value: ${{ steps.set-artifact-name.outputs.ARTIFACT_NAME }}
runs:
  using: composite
  steps:
   - name: Set BUILD_DIR
      id: set-build-dir
      shell: bash
      run: |
        if [ "$PLATFORM" == "android" ]; then
          echo "BUILD_DIR=android/app/build/outputs/apk/release" >> $GITHUB_OUTPUT
        elif [ "$PLATFORM" == "ios" ]; then
          echo "BUILD_DIR=ios/build" >> $GITHUB_OUTPUT
        else
          echo "Unsupported platform: $PLATFORM"
          exit 1
        fi

    - name: Set ARTIFACT_NAME
      id: set-artifact-name
      shell: bash
      run: |
        VERSION=$(node -p "require('./package.json').version")
        COMMIT_SHA=$(git rev-parse --short HEAD)
        if [ "$PLATFORM" == "android" ]; then
          echo "ARTIFACT_NAME=app-release-${VERSION}-${COMMIT_SHA}.apk" >> $GITHUB_OUTPUT
        elif [ "$PLATFORM" == "ios" ]; then
          echo "ARTIFACT_NAME=app-release-${VERSION}-${COMMIT_SHA}.ipa" >> $GITHUB_OUTPUT
        else
          echo "Unsupported platform: $PLATFORM"
          exit 1
        fi