name: 'Set up deploy environment'
description: 'Determine deploy env build and info based on platform'

inputs:
  ARTIFACT_NAME:
    description: 'The artifact name directory from the previous job'
    required: true

runs:
  using: composite
  steps:
    # Step to get info_file and build_file paths dynamically
    - name: Set up deploy environment
      id: setup_deploy_env
      run: |
        if [ "${{ matrix.platform }}" == "android" ]; then
          # Find .apk or .json file inside the artifact directory
          INFO_FILE=$(find ./${{ inputs.artifact_name }} -type f -name "*.json" | head -n 1)
          BUILD_FILE=$(find ./${{ inputs.artifact_name }} -type f -name "*.apk" | head -n 1)
        elif [ "${{ matrix.platform }}" == "ios" ]; then
          # Find .plist, .ipa, or .json file inside the artifact directory
          INFO_FILE=$(find ./${{ inputs.artifact_name }} -type f -name "*.plist" | head -n 1)
          BUILD_FILE=$(find ./${{ inputs.artifact_name }} -type f -name "*.ipa" | head -n 1)
        fi

        # Ensure the files are found
        if [ -z "$INFO_FILE" ] || [ -z "$BUILD_FILE" ]; then
          echo "Error: Required files not found!"
          exit 1
        fi

        echo "INFO_FILE=$INFO_FILE" >> $GITHUB_ENV
        echo "BUILD_FILE=$BUILD_FILE" >> $GITHUB_ENV
      shell: bash
