name: 'Set up deploy environment'
description: 'Determine deploy env build and info based on platform'
runs:
  using: composite
  steps:
    - name: Setup deploy environment for Android
      if: ${{ env.PLATFORM == 'android' }}
      run: |
        BUILD_FILE="${{ needs.get-app-name.outputs.app_name }}_${{ env.ENVIRONMENT }}_V_$(node -p "require('./package.json').version").${{ github.run_number }}.apk"
        INFO_FILE="${{ github.workspace }}/android/app/build/outputs/apk/release/output-metadata.json"
        
        if [[ -f "$BUILD_FILE" && -f "$INFO_FILE" ]]; then
          echo "BUILD_FILE=$BUILD_FILE" >> $GITHUB_ENV
          echo "INFO_FILE=$INFO_FILE" >> $GITHUB_ENV
        else
          echo "Required files not found!" >&2
          exit 1
        fi
      shell: bash

    - name: Setup deploy environment for iOS
      if: ${{ env.PLATFORM == 'ios' }}
      run: |
        BUILD_FILE="ios/build/${{ secrets.APP_NAME }}.ipa"
        INFO_FILE="ios/build/${{ secrets.APP_NAME }}-info.plist"

        if [[ -f "$BUILD_FILE" && -f "$INFO_FILE" ]]; then
          echo "BUILD_FILE=$BUILD_FILE" >> $GITHUB_ENV
          echo "INFO_FILE=$INFO_FILE" >> $GITHUB_ENV
        else
          echo "Required files not found!" >&2
          exit 1
        fi
      shell: bash