name: 'Set up build environment'
description: 'Determine build directory and artifact name based on platform'
runs:
  using: composite
  steps:
    - name: Setup build environment for Android
      if: ${{ env.PLATFORM == 'android' }}
      run: |
        BUILD_DIR="${{ github.workspace }}/android/app/build/outputs/apk/release"
        ARTIFACT_NAME="android-${{ env.ENVIRONMENT }}-${{ github.sha }}"
        
        echo "BUILD_DIR=$BUILD_DIR" >> $GITHUB_ENV
        echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_ENV
      shell: bash

    - name: Setup build environment for iOS
      if: ${{ env.PLATFORM == 'ios' }}
      run: |
        BUILD_DIR="${{ github.workspace }}/ios/build"
        ARTIFACT_NAME="ios-${{ env.ENVIRONMENT }}-${{ github.sha }}"
        
        echo "BUILD_DIR=$BUILD_DIR" >> $GITHUB_ENV
        echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_ENV
      shell: bash

    - name: Set gradlew permissions
      if: ${{ env.PLATFORM == 'android' }}
      run: chmod +x android/gradlew
      shell: bash

    - name: Setup keystore file
      if: ${{ env.PLATFORM == 'android' }}
      run: |
        echo "${{ env.KEYSTORE_FILE }}" | base64 --decode > ${{ env.ANDROID_KEYSTORE_FILE }}
      shell: bash