name: 'Set up build environment'
description: 'Determine build directory and artifact name based on platform'
outputs:
  build_dir:
    description: 'Path to the build output directory'
  artifact_name:
    description: 'Name for the build artifact'
runs:
  using: composite
  steps:
    - run: |
        if [ "${{ env.PLATFORM  }}" == "ios" ]; then
          echo "build_dir=${{ github.workspace }}/ios/build" >> $GITHUB_ENV
        else
          echo "build_dir=${{ github.workspace }}/android/app/build/outputs/apk/release" >> $GITHUB_ENV
        fi
        echo "artifact_name=${{ env.PLATFORM  }}-${{ env.PLATFORM }}-${{ github.sha }}" >> $GITHUB_ENV
      shell: bash

    - name: Set gradlew permissions
      if: ${{ env.PLATFORM == 'android' }}
      run: chmod +x android/gradlew
      shell: bash

    - name: Setup keystore file
      if: ${{ env.PLATFORM == 'android' }}
      run: |
        echo "${{ env.KEYSTORE_FILE }}" | base64 --decode > ${{ env.ANDROID_KEYSTORE_FILE }}
      shell: bash
