name: 'Cache Restore'

description: 'Restores cached dependencies for Node.js, CocoaPods, Ruby gems, and Fastlane plugins.'

runs:
  using: 'composite'
  steps:
    - name: Restore Node.js modules cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-

    - name: Restore CocoaPods cache
      if: ${{ env.PLATFORM == 'ios' }}
      uses: actions/cache@v4
      with:
        path: |
          ios/Pods
          ios/Podfile.lock
        key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-

    - name: Restore Ruby gems cache
      uses: actions/cache@v4
      with:
        path: |
          vendor/bundle
        key: ${{ runner.os }}-bundler-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-bundler-

    - name: Install Ruby dependencies
      run: |
        if [ -d "vendor/bundle" ] && [ "$(ls -A vendor/bundle)" ]; then
          ls -l vendor/bundle/ruby
          echo "Using cached gems"
        else
          echo "No cached gems found or vendor/bundle is empty. Installing gems..."
          bundle install
        fi
      shell: bash
