name: 'Set up build environment'
description: 'Determine build directory and artifact name based on platform'
runs:
  using: composite
  steps:
    - name: Setup build environment android dir
      if: ${{ env.PLATFORM == 'android' }}
      run: |
        echo "BUILD_DIR=${{ github.workspace }}/android/app/build/outputs/apk/${{ env.ENVIRONMENT == 'prod' ? 'release' : 'qa'}}" >> $GITHUB_ENV
        echo "ARTIFACT_NAME=android-${{ env.ENVIRONMENT }}-${{ github.sha }}" >> $GITHUB_ENV
      shell: bash

    - name: Setup build environment ios dir
      if: ${{ env.PLATFORM == 'ios' }}
      run: |
        echo "BUILD_DIR=${{ github.workspace }}/ios/build" >> $GITHUB_ENV
        echo "ARTIFACT_NAME=ios-${{ env.ENVIRONMENT }}-${{ github.sha }}" >> $GITHUB_ENV
      shell: bash

    - name: Set gradlew permissions
      if: ${{ env.PLATFORM == 'android' }}
      run: chmod +x android/gradlew
      shell: bash

    - name: Setup keystore file
      if: ${{ env.PLATFORM == 'android' }}
      run: |
        echo "${{ env.KEYSTORE_FILE }}" | base64 --decode > ${{ env.ANDROID_KEYSTORE_FILE }}
      shell: bash
