name: 'Set up build environment'
description: 'Determine build directory and artifact name based on platform'
runs:
  using: composite
  steps:
    - name: Setup build environment
      run: |
        if [[ "${{ env.PLATFORM }}" == "android" ]]; then
          echo "BUILD_DIR=${{ github.workspace }}/android/app/build/outputs/apk/release" >> $GITHUB_OUTPUT
          echo "ARTIFACT_NAME=android-${{ env.ENVIRONMENT }}-${{ github.sha }}" >> $GITHUB_OUTPUT
        elif [[ "${{ env.PLATFORM }}" == "ios" ]]; then
          echo "BUILD_DIR=${{ github.workspace }}/ios/build" >> $GITHUB_OUTPUT
          echo "ARTIFACT_NAME=ios-${{ env.ENVIRONMENT }}-${{ github.sha }}" >> $GITHUB_OUTPUT
        else
          echo "Unsupported platform: ${{ env.PLATFORM }}" >&2
          exit 1
        fi
      shell: bash

    - name: Set gradlew permissions
      if: ${{ env.PLATFORM == 'android' }}
      run: chmod +x android/gradlew
      shell: bash

    - name: Setup keystore file
      if: ${{ env.PLATFORM == 'android' }}
      run: |
        echo "${{ env.KEYSTORE_FILE }}" | base64 --decode > ${{ env.ANDROID_KEYSTORE_FILE }}
      shell: bash