name: 'Set up build environment'
description: 'Set up the build environment and determine build directory'
outputs:
  BUILD_DIR:
    description: 'Directory where build artifacts are stored'
    value: ${{ steps.set_build_dir.outputs.BUILD_DIR }}
  ARTIFACT_NAME:
    description: 'Name of the artifact to be uploaded'
    value: ${{ steps.set_artifact_name.outputs.ARTIFACT_NAME }}
inputs:
  ENV_PROD:
    description: 'Environment variable for production'
  ENV_STAGING:
    description: 'Environment variable for staging'
  ENV_BETA:
    description: 'Environment variable for beta'
  ENV_DEV:
    description: 'Environment variable for development'

runs:
  using: composite
  steps:
    - name: Create .env file
      shell: bash
      run: |
        ENVIRONMENT="${{ env.ENVIRONMENT }}"

        if [[ "$ENVIRONMENT" == "production" ]]; then
          ENV_CONTENT="${{ inputs.ENV_PROD }}"
        elif [[ "$ENVIRONMENT" == "staging" ]]; then
          ENV_CONTENT="${{ inputs.ENV_STAGING }}"
        elif [[ "$ENVIRONMENT" == "development" ]]; then
          ENV_CONTENT="${{ inputs.ENV_DEV }}"
        elif [[ "$ENVIRONMENT" == "beta" ]]; then
          ENV_CONTENT="${{ inputs.ENV_BETA }}"
        else
          echo "Unknown environment: $ENVIRONMENT" >&2
          exit 1
        fi

        # Create the .env file
        ENV_FILE="configuration/.env.$ENVIRONMENT"
        ROOT_ENV_FILE="${{ github.workspace }}/.env"
        echo "$ENV_CONTENT" > "$ENV_FILE"
        echo "$ENV_CONTENT" > "$ROOT_ENV_FILE"
        ENV_FILE_PATH="configuration/.env.$ENVIRONMENT"
        echo "ENVFILE=$ENV_FILE_PATH" >> $GITHUB_ENV

        # Check if the .env file was created
        if [[ -f "$ENV_FILE" ]]; then
          echo ".env file created successfully: $ENV_FILE"
          
          # Verify the content of the .env file
          FILE_CONTENT=$(<"$ENV_FILE")
          if [[ "$FILE_CONTENT" == "$ENV_CONTENT" ]]; then
            echo "The .env file has the correct content."
            echo "Content of the .env file:"
            echo "$FILE_CONTENT"  # Show the content of the .env file
          else
            echo "The .env file does not have the expected content." >&2
            exit 1
          fi
        else
          echo "Failed to create .env file: $ENV_FILE" >&2
          exit 1
        fi

    - name: Set build directory
      id: set_build_dir
      run: |
        if [[ "${{ env.PLATFORM }}" == "android" ]]; then
          echo "BUILD_DIR=${{ github.workspace }}/android/app/build/outputs/apk" >> $GITHUB_OUTPUT
        elif [[ "${{ env.PLATFORM }}" == "ios" ]]; then
         echo "BUILD_DIR=${{ github.workspace }}/ios/build/" >> $GITHUB_OUTPUT
        else
          echo "Unsupported platform: ${{ env.PLATFORM }}" >&2
          exit 1
        fi
      shell: bash

    - name: Set artifact name
      id: set_artifact_name
      shell: bash
      run: |
        ARTIFACT_NAME="${{ env.ENVIRONMENT }}-build-${{ github.sha }}"
        echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_OUTPUT

    - name: Set gradlew permissions
      if: ${{ env.PLATFORM == 'android' }}
      run: chmod +x android/gradlew
      shell: bash
