name: Install dependencies
description: Install dependencies for different platforms

runs:
  using: composite
  steps:
    - name: cache node modules
      uses: ./.github/actions/cache-action

    - name: Install Node dependencies
      run: yarn install --frozen-lockfile
      shell: bash

    # Step 6: Cache Ruby gems to speed up future builds
    - name: Restore Ruby gems cache
      uses: actions/cache@v4
      id: cache-gems
      with:
        path: vendor/bundle # Directory to cache for Ruby gems
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    # Step 7: Install Ruby dependencies
    - name: Install Ruby dependencies
      run: |
        bundle install --jobs 4 --retry 3 # Install gems with parallel jobs and retry on failure
      shell: bash
