name: Install dependencies
description: Install dependencies for different platforms

runs:
  using: composite
  steps:
    - name: cache node modules
      uses: ./.github/actions/cache-action

    - name: Install Node dependencies
      run: yarn install --frozen-lockfile
      shell: bash

    # Step 6: Cache Ruby gems to speed up future builds
    - name: Restore Ruby gems cache
      uses: actions/cache@v4
      id: cache-gems
      with:
        path: vendor/bundle # Directory to cache for Ruby gems
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }} # Cache key based on OS and Gemfile.lock hash
        restore-keys: |
          ${{ runner.os }}-gems- # Fallback key for restoring cache if the exact match is not found

    # Step 7: Install Ruby dependencies
    - name: Install Ruby dependencies
      run: |
        if [ "${{ steps.cache-gems.outputs.cache-hit }}" != 'true' ]; then # Check if gems cache was hit
          echo "Cache miss. Installing gems..." # Log message for cache miss
          bundle install --jobs 4 --retry 3 # Install gems with parallel jobs and retry on failure
        else
          echo "Using cached gems" # Log message for cache hit
          bundle install --local # Install gems from cache
        fi
      shell: bash
