name: 'iOS Environment Setup'

runs:
  using: 'composite'
  steps:
    - name: Set up Xcode
      run: |
        sudo xcode-select --switch /Applications/Xcode_15.3.app
        sudo xcodebuild -license accept
      shell: bash

    - name: Update Homebrew
      run: |
        brew update
      shell: bash

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.0'  # Match this to the Ruby version in the error message
        bundler-cache: true
        working-directory: '.'  # Ensure it's using the Gemfile in your project root

    - name: Install Ruby dependencies
      run: |
        gem install bundler
        bundle config set --local path 'vendor/bundle'
        bundle install --jobs 4 --retry 3
      shell: bash

