name: 'iOS Environment Setup'

runs:
  using: 'composite'
  steps:
    - name: Set up Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode_15.3.app
        sudo xcodebuild -license accept
      shell: bash

    - name: Cache Ruby gems
      uses: actions/cache@v4
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6.10'
        bundler-cache: true

    - name: Cache Fastlane plugins
      uses: actions/cache@v4
      with:
        path: fastlane/plugins
        key: ${{ runner.os }}-fastlane-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-fastlane-

    - name: Install dependencies and Fastlane
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
      shell: bash

    - name: Install Fastlane plugins
      run: bundle exec fastlane install_plugins
      shell: bash
