name: 'iOS Environment Setup'

runs:
  using: 'composite'
  steps:
    - name: Set up Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode_15.3.app
        sudo xcodebuild -license accept
      shell: bash

    - name: Cache Ruby gems
      uses: actions/cache@v4
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6.10'
        bundler-cache: true

    - name: Install Bundler 2.4.22
      run: gem install bundler -v 2.4.22
      shell: bash

    - name: Install bundler
      run: bundle install
      shell: bash

    - name: Cache Bundler gems
      uses: actions/cache@v4
      with:
        path: |
          vendor/bundle
          .bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Install Ruby dependencies
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
      shell: bash

    - name: Cache Fastlane plugins
      uses: actions/cache@v4
      with:
        path: fastlane/plugins
        key: ${{ runner.os }}-fastlane-${{ hashFiles('**/Gemfile.lock') }}

    - name: Install Fastlane
      run: bundle exec gem install fastlane
      shell: bash

    - name: Install Fastlane plugins
      run: bundle exec fastlane install_plugins
      shell: bash

    - name: Check CocoaPods installation
      run: bundle exec pod --version
      shell: bash

    - name: Check Ruby Environment
      run: |
        ruby -v
        which ruby
        gem env
        bundle --version
        bundle exec pod --version
        bundle exec fastlane --version
      shell: bash

    - name: Clear caches (if needed)
      if: failure()
      run: |
        rm -rf vendor/bundle
        rm -rf ~/.bundle
        rm -rf ios/Pods
        rm -rf ~/Library/Caches/CocoaPods
      shell: bash
