name: 'iOS Environment Setup'

runs:
  using: 'composite'
  steps:
    - name: Set up Xcode
      run: |
        sudo xcode-select --switch /Applications/Xcode_15.3.app
        sudo xcodebuild -license accept
      shell: bash

    - name: Cache Bundler gems
      uses: actions/cache@v4
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-bundler-${{ hashFiles('Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-bundler-


    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6.10'
        bundler-cache: true  # Disable built-in caching

    - uses: actions/cache@v4
      with:
        path: vendor/bundle
        key: bundle-use-ruby-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          bundle-use-ruby-
    - name: Bundle install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
      shell: bash

    - name: Check Ruby Version
      run: |
        ruby -v
      shell: bash

    - name: Check Bundler Path
      run: |
          bundle config get path
          ls -la vendor/bundle
      shell: bash
    