 
 name: Upload APK Version

inputs:
  AUTHORIZATION:
    description: 'Authorization token'
    required: true
  APP_DEV_TOKEN:
    description: 'Application dev token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Download Android Artifacts
      uses: actions/download-artifact@v4
      with:
        name: android-release
        path: ${{ env.IOS_BUILD_FILE }}

    - name: Upload the application on Mstore
     
      run: |
       bundle exec fastlane upload_ios_to_mstore
      shell: bash

    - name: Upload iOS version to MStore
      run: |
        fastlane ios upload_to_mstore
      shell: bash