name: 'Build Android'

runs:
  using: 'composite'
  steps:
    - name: Grant execute permission for gradlew
      run: |
        cd android
        chmod +x gradlew

    - name: Clean the project
      run: |
        cd android
        ./gradlew clean

    - name: Install and Build SDK for Android
      run: |
        mkdir -p android/app/src/main/assets
        yarn react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Build Android Release
      run: cd android && ./gradlew assembleRelease

    - name: Upload Android Artifact
      uses: actions/upload-artifact@v3
      with:
        name: android-release
        path: android/app/build/outputs/apk/release/app-release.apk
