name: 'Build ANDROID'

runs:
  using: 'composite'
  steps:
    - name: Restore node modules from cache
      uses: ./.github/actions/cache-restore

    - name: Restore cache
      uses: actions/cache@v3
      with:
              path: |
                vendor/bundle
              key: ${{ runner.os }}-bundler-${{ hashFiles('**/Gemfile.lock') }}

    - name: Set gradlew permissions
      run: chmod +x android/gradlew
      shell: bash

    - name: Decode Keystore
      run: |
        echo "${{ env.KEYSTORE_FILE }}" | base64 --decode > ${{ env.ANDROID_KEYSTORE_FILE }}
      shell: bash

    - name: Build Android with Fastlane
      run: |
        bundle exec fastlane android build
      shell: bash

    - name: Upload Android Artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-release
        path: |
          ${{ env.ANDROID_BUILD_DIR }}
        if-no-files-found: error
