name: 'Install dependencies'

runs:
  using: 'composite'
  steps:
    - name: 📦 Restore node modules from cache
      uses: ./.github/actions/cache-restore

    - name: 🚑  Run type check
      run: yarn typecheck
      shell: bash

    - name: 🏃‍♂️ Run tests with coverage
      run: yarn test --coverage
      shell: bash

   - name: Jest Coverage Comment
      uses: MishaKav/jest-coverage-comment@main
      if: (success() || failure()) && github.event_name == 'pull_request'
      with:
          coverage-summary-path: ./coverage/coverage-summary.json
          summary-title: "💯 Test Coverage"
          badge-title: Coverage
          create-new-comment: false
          junitxml-title: 😎 Tests Results
          junitxml-path: ./coverage/jest-junit.xml
          coverage-title: 👀 Tests Details
          coverage-path: ./coverage/coverage.txt
          report-only-changed-files: true
          
    #    - name: 🏃‍♂️ Run lint
    #      run: yarn lint
    #      shell: bash
