name: Code Quality Assurance & Repository Mirroring

on:
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened, closed]

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  code-checkout:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

  environment-setup:
    needs: code-checkout
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Android Environment Setup
        uses: ./.github/actions/build-test/android-setup/android-runner

      - name: IOS Environment Setup
        uses: ./.github/actions/build-test/ios-setup/ios-runner

  dependency-installation:
    needs: environment-setup
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/build-test/dependency-installation

  check-pr:
    runs-on: macos-latest
    needs: dependency-installation
    permissions:
      contents: read
      pull-requests: write
    env:
      PLATFORM: android
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check PR codeBase
        uses: ./.github/actions/build-test/pr-check

  sonarqube-scan:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Perform SonarQube scan
        uses: ./.github/actions/sonar-report
