name: Lint, Test, and Type Check
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  lint-test:
    name: Lint, Test, and Type Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # Checkout code from GitHub

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Yarn install with retries
        uses: Wandalen/wretry.action@master
        with:
          command: yarn --frozen-lockfile
          attempt_limit: 3
          attempt_delay: 2000

      - name: Cache Node.js modules for linting
        uses: actions/cache@v3 # Separate cache for linting
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-lint-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-lint-

      - name: Lint check
        run: ././scripts/lint.sh # Run linting script with relative path (adjust if needed)

      - name: Check for linting errors
        run: |
          if [[ $? -ne 0 ]]; then
            echo "Linting failed!"
            core.setFailed('Linting errors detected!')  # Use core.setFailed from actions/core
          fi

      - name: ✅ Run unit tests
        run: yarn test
        shell: bash

      - name: 🚀 Type check
        run: yarn type-check
        shell: bash

      - name: Install dotenv package
        run: npm install dotenv
        shell: bash

      - name: Set up environment variables from .env
        run: |
          export $(cat .env | grep -v '#' | xargs)
        shell: bash

      - name: Build APK and Setup JDK
        uses: ./.github/actions/build
        with:
          APP_ENV: ${{ env.APP_ENV }}
