name: CI/CD Pipeline

on:
  push:
    branches: [master, develop, main]
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened]

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to build for'
        required: true
        default: 'staging'
        type: choice
        options:
          - prod
          - staging
          - dev
          - beta

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  CI: true

jobs:
  prepare-environment:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup android environment
        uses: ./.github/actions/build-test/android-setup/android-runner
      - name: Setup ios environment
        uses: ./.github/actions/build-test/ios-setup/ios-runner

  install-dependencies:
    runs-on: macos-latest
    needs: prepare-environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        uses: ./.github/actions/build-test/dependency-installation

  quality-checks:
    needs: install-dependencies
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check PR codeBase
        uses: ./.github/actions/build-test/pr-check

      # - name: Perform SonarQube scan
      #   uses: ./.github/actions/build-test/sonar-report
      #   env:
      #     SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
      #     SONARQUBE_HOST: ${{ secrets.SONARQUBE_HOST }}

  get-app-name:
    runs-on: ubuntu-latest
    outputs:
      app_name: ${{ steps.get_app_name.outputs.APP_NAME }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get app name
        id: get_app_name
        run: |
          APP_NAME=$(node -p "require('./package.json').name")
          echo "APP_NAME=${APP_NAME}" >> $GITHUB_OUTPUT
        shell: bash

  build:
    needs: [get-app-name, quality-checks]
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: macos-latest
    strategy:
      matrix:
        platform: [android]
    env:
      PLATFORM: ${{ matrix.platform }}
      ENVIRONMENT: ${{ github.event.inputs.environment || 'staging' }}
      ANDROID_KEYSTORE_FILE: ${{ github.workspace }}/android/app/release.keystore
      KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore node modules from cache
        uses: ./.github/actions/cache-restore

      - name: Set up environment
        id: setup_env
        uses: ./.github/actions/setup-build-env

      - name: Build ${{ matrix.platform }}
        run: |
          bundle exec fastlane ${{ matrix.platform }} build
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.setup_env.outputs.artifact_name }}
          path: ${{ steps.setup_env.outputs.build_dir }}

    outputs:
      build_dir: ${{ steps.setup_env.outputs.build_dir }}
      artifact_name: ${{ steps.setup_env.outputs.artifact_name }}

  deploy:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    needs: [get-app-name, build]
    runs-on: macos-latest
    strategy:
      matrix:
        platform: [android]
    env:
      PLATFORM: ${{ matrix.platform }}
      ENVIRONMENT: ${{ github.event.inputs.environment || 'staging' }} # Default to 'staging' if not provided

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore node modules from cache
        uses: ./.github/actions/cache-restore

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact_name }}
          path: ${{ needs.build.outputs.build_dir }}

      - name: Upload ${{ matrix.platform }} - ${{ env.ENVIRONMENT }} the application on MStore
        if: ${{ env.ENVIRONMENT }} != 'prod'
        run: |
          bundle exec fastlane upload_app_to_mstore
        env:
          AUTHORIZATION: ${{ secrets.AUTHORIZATION }}
          APP_DEV_TOKEN: ${{ secrets.APP_DEV_TOKEN }}
          BUILD_FILE: ${{ needs.build.outputs.build_file }}
          INFO_FILE: ${{ needs.build.outputs.info_file }}
        shell: bash

      - name: Upload ${{ matrix.platform }} - ${{ env.ENVIRONMENT }} the application on store
        if: ${{ env.ENVIRONMENT }} == 'prod'
        run: |
          echo "This step will be added in the future"
        shell: bash

  notify-teams:
    if: github.event_name == 'push'
    needs: deploy
    runs-on: macos-latest
    steps:
      - name: Notify teams
        uses: ./.github/actions/teams-notify
        with:
          status: ${{ job.status }}
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          custom_message: 'New version is available on MStore'
