name: Lint, Test, and Type Check
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint-test:
    name: Lint, Test, and Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js, Yarn, and Dependencies
        uses: ./actions/node-setup.yml
        with:
          node-version: 19

      - name: Install dotenv package
        run: npm install dotenv
        shell: bash

      - name: Set up environment variables from .env
        run: |
          export $(cat .env | grep -v '#' | xargs)
        shell: bash

      - name: Build APK and Setup JDK
        uses: ./actions/build.yml
        with:
          APP_ENV: ${{ env.APP_ENV }}

      - name: 🧹 Lint code
        run: yarn lint
        shell: bash

      - name: ✅ Run unit tests
        run: yarn test
        shell: bash

      - name: 🚀 Type check
        run: yarn typecheck
        shell: bash
