name: CI/CD Pipeline

on:
  push:
    branches: [master, develop, main]
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened, closed]

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  APP_NAME: ${{ secrets.APP_NAME }}
  CI: true
  ANDROID_KEYSTORE_FILE: ${{ github.workspace }}/android/app/release.keystore
  ANDROID_BUILD_DIR: ${{ github.workspace }}/android/app/build/outputs/apk/release
  ANDROID_BUILD_FILE: ${{ github.workspace }}/android/app/build/outputs/apk/release/app-release.apk
  ANDROID_INFO_FILE: ${{ github.workspace }}/android/app/build/outputs/apk/release/output-metadata.json
  IOS_BUILD_FILE: ios/build/${{ secrets.APP_NAME }}.ipa
  IOS_INFO_FILE: ios/build/${{ secrets.APP_NAME }}-info.plist
  SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
  SONARQUBE_HOST: ${{ secrets.SONARQUBE_HOST }}
  SONAR_PROJECT_KEY: $(grep '^sonar.projectKey=' sonar-project.properties | cut -d'=' -f2-)" >> $GITHUB_ENV
jobs:
  setup:
    runs-on: macos-latest
    outputs:
      repo-path: ${{ steps.upload.outputs.artifact-path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Upload repository
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: repo
          path: .

  prepare:
    needs: setup
    runs-on: macos-latest
    steps:
      - name: Download repository
        uses: actions/download-artifact@v4
        with:
          name: repo
      - name: Setup android environment
        uses: ./.github/actions/build-test/android-setup/android-runner
      - name: Setup ios environment
        uses: ./.github/actions/build-test/ios-setup/ios-runner
      - name: Install dependencies
        uses: ./.github/actions/build-test/dependency-installation

  quality-checks:
    needs: prepare
    runs-on: macos-latest
    timeout-minutes: 10

    steps:
      - name: Download repository
        uses: actions/download-artifact@v4
        with:
          name: repo
      - name: Check PR codeBase
        uses: ./.github/actions/build-test/pr-check

      - name: Perform SonarQube scan
        uses: ./.github/actions/build-test/sonar-report

  mirror-exclusions:
    if: github.event_name == 'push'
    runs-on: macos-latest
    needs: quality-checks
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update script permissions
        run: chmod +x ./.github/scripts/create-mirror.sh

      - name: Create mirror repository
        run: ./.github/scripts/create-mirror.sh
      - name: Upload repository
        uses: actions/upload-artifact@v4
        with:
          name: clean-repo
          path: clean-repo.zip

  build-ios:
    if: github.event_name == 'push'
    needs: mirror-exclusions
    runs-on: macos-latest
    steps:
      - name: Download repository
        uses: actions/download-artifact@v4
        with:
          name: repo
      - name: Build iOS
        uses: ./.github/actions/build-test/ios-setup/ios-build
        env:
          PLATFORM: ios

  build-android:
    if: github.event_name == 'push'
    needs: mirror-exclusions
    runs-on: macos-latest
    steps:
      - name: Download repository
        uses: actions/download-artifact@v4
        with:
          name: repo
      - name: Build Android
        uses: ./.github/actions/build-test/android-setup/android-build
        env:
          PLATFORM: android

  deploy-android:
    if: github.event_name == 'push'
    needs: build-android
    runs-on: macos-latest
    steps:
      - name: Download repository
        uses: actions/download-artifact@v4
        with:
          name: repo
      - name: Upload Android to MStore
        uses: ./.github/actions/mstore-upload/android-upload
        with:
          AUTHORIZATION: ${{ secrets.AUTHORIZATION }}
          APP_DEV_TOKEN: ${{ secrets.APP_DEV_TOKEN }}
      - name: Notify teams - Android
        uses: ./.github/actions/teams-notify
        with:
          status: ${{ job.status }}
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          custom_message: 'New Android version is available on MStore'

  deploy-ios:
    if: github.event_name == 'push'
    needs: build-ios
    runs-on: macos-latest
    steps:
      - name: Download repository
        uses: actions/download-artifact@v4
        with:
          name: repo
      - name: Upload iOS App
        uses: ./.github/actions/app-upload/upload
        with:
          AUTHORIZATION: ${{ secrets.AUTHORIZATION }}
          APP_DEV_TOKEN: ${{ secrets.APP_DEV_TOKEN }}
          info-file: ${{ env.IOS_INFO_FILE }}
          build-file: ${{ env.IOS_BUILD_FILE }}
      - name: Notify teams - iOS
        uses: ./.github/actions/teams-notify
        with:
          status: ${{ job.status }}
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          custom_message: 'New iOS version is available on MStore'
