name: Lint, Unit Tests, and Code Analysis

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
    types: [opened, synchronize]

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  ENV: DEVELOPMENT

jobs:
  download-dependencies:
    runs-on: macos-latest
    steps:
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

  check-pr:
    runs-on: macos-latest
    needs: download-dependencies
    steps:
      - name: Common Setup
        uses: ./.github/actions/common-setup
      - name: Check PR codeBase
        uses: ./.github/actions/check-pr

  build-ios:
    runs-on: macos-latest
    needs: check-pr
    steps:
      - name: Common Setup
        uses: ./.github/actions/common-setup
      - name: build ios
        uses: ./.github/actions/build-ios

  build-android:
    runs-on: macos-latest
    needs: check-pr
    steps:
      - name: Common Setup
        uses: ./.github/actions/common-setup
      - name: build android
        uses: ./.github/actions/build-android
