name: Lint, Unit Tests, and Code Analysis

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
    types: [opened, synchronize]

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  APP_NAME: ${{ github.repository }}
  ENV: # Define an empty ENV variable to be populated later

jobs:
  download-dependencies:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Load .env variables for Download Dependencies
        run: |
          bash .github/actions/load-env-vars.sh
          echo "ENV=${ENV}" >> $GITHUB_ENV  # Export ENV variable to GitHub Actions environment

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

  check-pr:
    runs-on: macos-latest
    needs: download-dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore node modules from cache
        uses: ./.github/actions/common-setup

      - name: Check PR codeBase
        uses: ./.github/actions/pr-check

  build-ios:
    runs-on: macos-latest
    needs: check-pr
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore node modules from cache
        uses: ./.github/actions/common-setup

      - name: Build iOS
        uses: ./.github/actions/build-ios

  build-android:
    runs-on: macos-latest
    needs: check-pr
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore node modules from cache
        uses: ./.github/actions/common-setup

      - name: Build Android
        uses: ./.github/actions/build-android
