name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - develop
      - main
      - 'v[0-9]+.[0-9]+.[0-9]+*beta*'
    types: [opened, synchronize]
  push:
    branches:
      - develop
      - main
      - 'v[0-9]+.[0-9]+.[0-9]+*beta*'

jobs:
  build:
    uses: ./.github/workflows/build.yml

  restore_workspace:
    name: Restore Workspace
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download workspace archive
        uses: actions/download-artifact@v3
        with:
          name: workspace
          path: .

      - name: Extract workspace
        run: tar -xzf workspace.tar.gz

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: restore_workspace
    env:
      NODE_ENV: test
      CI: true

    steps:
      - name: Run unit tests
        run: yarn test --forceExit

      - name: Run coverage
        run: yarn test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  lint:
    name: Run Lint Check
    runs-on: ubuntu-latest
    needs: restore_workspace

    steps:
      - name: Lint check
        run: ./scripts/lint.sh

  format:
    name: Run Format Check
    runs-on: ubuntu-latest
    needs: restore_workspace

    steps:
      - name: Prettier check
        run: yarn prettify

  typecheck:
    name: Run Type Check
    runs-on: ubuntu-latest
    needs: restore_workspace

    steps:
      - name: Type check
        run: yarn typecheck

  security:
    name: Run Snyk Security Scan
    runs-on: ubuntu-latest
    needs: restore_workspace
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      - name: Snyk Security Scan
        uses: snyk/actions/node@master
        with:
          command: test
