name: Lint and Test

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  linting:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Yarn install
        uses: Wandalen/wretry.action@master
        with:
          command: yarn --frozen-lockfile
          attempt_limit: 3
          attempt_delay: 2000

      - name: Lint check
        run: yarn lint

      - name: Prettier check
        run: yarn prettify

      - name: Type check
        run: yarn typecheck

  testing:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Yarn install
        uses: Wandalen/wretry.action@master
        with:
          command: yarn --frozen-lockfile
          attempt_limit: 3
          attempt_delay: 2000

      - name: Run tests
        run: yarn test --forceExit
