name: Lints

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  linting:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # Checkout code from GitHub

      - name: Set up Node.js
        uses: actions/setup-node@v4  # Consistent version with test.yml

      - name: Yarn install with retries
        uses: Wandalen/wretry.action@master
        with:
          command: yarn --frozen-lockfile
          attempt_limit: 3
          attempt_delay: 2000

      - name: Cache Node.js modules for linting
        uses: actions/cache@v3  # Separate cache for linting
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-lint-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-lint-

      - name: Check for linting errors
        run: |
          if [[ $(yarn lint 2>&1) ]]; then
            echo "Linting failed!"
          fi
          core.setFailed('Linting errors detected!')

      - name: Prettier check
        run: yarn prettify  

      - name: Type check (if applicable)
        run: yarn typecheck  
