name: 'PR Labeler and Reviewer Assigner'

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  label-and-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Reviewer Assignment (only on opened PRs)
      - name: Assign Reviewers
        if: github.event.action == 'opened'
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: .github/auto_assign.yml

      # Labeling
      - name: Label PR
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
