name: 'Pull Request Labeler and Reviewer Assigner' # More descriptive name

on:
  pull_request:
    types: [opened, edited]

jobs:
  label-and-assign:
    runs-on: macos-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      # Reviewer Assignment (only on opened PRs)
      - name: Assign Reviewers (Only on Opened PR)
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration_path: ./.github/auto_assign.yml

      # Labeling (potentially with conditions)
      - name: Update Labels (Consider conditions)
        uses: actions/labeler@v5
        with:
          configuration_file: ./.github/labeler.yml
