name: 'PR Labeler and Reviewer Assigner'

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, closed]


jobs:
  label-and-assign:
    runs-on: macos-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      # Reviewer Assignment (only on opened PRs)
      - name: Assign Reviewers (Only on Opened PR)
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: ./.github/auto_assign.yml

      # Labeling (potentially with conditions)
      - name: Update Labels
        if: github.event.action == 'opened' || github.event.action == 'edited'
        uses: actions/labeler@v5
        with:
          configuration-path: ./.github/labeler.yml
