name: 'Pull Request Labeler and Reviewer Assigner' # More descriptive name

on:
  pull_request: # Trigger on pull request events
    types: [opened, edited] # For both opened and edited PRs

jobs:
  label-and-assign: # Combined job name for clarity
    runs-on: ubuntu-latest
    permissions: # Combined permissions for all steps
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4 # Checkout the repository code (implicitly assumed)

      # Reviewer Assignment (only on opened PRs)
      - name: Assign Reviewers (Only on Opened PR)
        uses: kentaro-m/auto-assign-action@v2.0.0 # Assign reviewers
        with:
          configuration_path: '.github/auto_assign.yml' # Default path
        if: github.event.action == 'opened' # Only run on pull_request opened event

      # Labeling (potentially with conditions)
      - name: Update Labels (Consider conditions)
        uses: actions/labeler@v5 # Label the pull request
        with:
          configuration_file: .github/labels.yml
