name: 'PR Labeler and Reviewer Assigner'

on:
  pull_request:
    types: [opened, ready_for_review]
    branches: [main, develop]

jobs:
  label-and-assign:
    runs-on: engagement-runner
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Assign Reviewers
        if: github.event.action == 'opened'
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: .github/auto_assign.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Label PR
        uses: actions/labeler@v5
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: .github/labeler.yml
