name: 'Setup Ruby'

on:
  workflow_call:
    inputs:
      ruby-version:
        required: true
        type: string

jobs:
  setup:
    runs-on: macos-latest
    steps:
      - name: Set up Xcode
        run: |
          sudo xcode-select --switch /Applications/Xcode_15.3.app
          sudo xcodebuild -license accept
        shell: bash

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ inputs.ruby-version }}
          bundler-cache: true

      - name: Check Ruby Version
        run: ruby -v
        shell: bash

      - name: Install Bundler and Dependencies
        run: |
          gem install bundler -v 2.4.22
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
        shell: bash
